with-expecter: true
dir: "_mocks/{{.PackagePath}}"
# new from v2.49.0, for more detail please refer to:
# https://github.com/vektra/mockery/commit/13fc60740a1eab3fc705fcc131a4b9a6eacfd0fe#diff-4bc8f03915f15ecf2cb9965592fcf933bb06986003613b5633a8dea7962c31a9R40
resolve-type-alias: false
packages:
  io:
    config:
    interfaces:
      Reader:
  github.com/aitra-ai/aitra-server/component:
    config:
      all: true
    interfaces:
      RepoComponent:
        config:
          mock-build-tags: "!saas && !ee"
  github.com/aitra-ai/aitra-server/component/reporter:
    config:
    interfaces:
      LogCollector:
  github.com/aitra-ai/aitra-server/component/reporter/sender:
    config:
    interfaces:
      LogSender:

  github.com/aitra-ai/aitra-server/component/checker:
    config:
    interfaces:
      GitCallbackChecker:
  github.com/aitra-ai/aitra-server/component/callback:
    config:
    interfaces:
      SyncVersionGenerator:
      GitCallbackComponent:
  github.com/aitra-ai/aitra-server/user/component:
    config:
    interfaces:
      MemberComponent:
      OrganizationComponent:
      JwtComponent:
      UserComponent:
      AccessTokenComponent:
      InvitationComponent:
      UserPhoneComponent:
  github.com/aitra-ai/aitra-server/payment/component:
    config:
    interfaces:
      PaymentComponent:
      StripeComponent:
  github.com/aitra-ai/aitra-server/moderation/component:
    interfaces:
      RepoComponent:
      SensitiveComponent:
      SensitiveWordSetComponent:
  github.com/aitra-ai/aitra-server/builder/geo:
    config:
      all: True
  github.com/aitra-ai/aitra-server/builder/store/database:
    config:
      all: True
  github.com/aitra-ai/aitra-server/builder/store/database/ee:
    config:
      all: True
      mock-build-tags: "saas || ee"
  github.com/aitra-ai/aitra-server/builder/rpc:
    config:
    interfaces:
      UserSvcClient:
      ModerationSvcClient:
      NotificationSvcClient:
      PaymentSvcClient:
      SSOInterface:
      AgentHubSvcClient:
      XnetSvcClient:
      CsgbotSvcClient:
  github.com/aitra-ai/aitra-server/builder/llm:
    config:
    interfaces:
      LLMSvcClient:
  github.com/aitra-ai/aitra-server/builder/sensitive:
    config:
    interfaces:
      GreenClient:
      Green2022Client:
      SensitiveChecker:
  github.com/aitra-ai/aitra-server/builder/proxy:
    config:
    interfaces:
      ReverseProxy:
  github.com/aitra-ai/aitra-server/builder/git/gitserver:
    config:
    interfaces:
      GitServer:
  github.com/aitra-ai/aitra-server/builder/git/mirrorserver:
    config:
    interfaces:
      MirrorServer:
  github.com/aitra-ai/aitra-server/builder/git/membership:
    config:
    interfaces:
      GitMemerShip:
  github.com/aitra-ai/aitra-server/builder/rsa:
    config:
    interfaces:
      KeysReader:
  github.com/aitra-ai/aitra-server/builder/prometheus:
    config:
    interfaces:
      PrometheusClient:
  github.com/aitra-ai/aitra-server/builder/mq:
    config:
    interfaces:
      MessageQueueFactory:
      MessageQueue:
  github.com/aitra-ai/aitra-server/mirror/cache:
    config:
    interfaces:
      Cache:
  github.com/aitra-ai/aitra-server/mirror/hook:
    config:
    interfaces:
      MessageSender:
  github.com/aitra-ai/aitra-server/mirror/filter:
    config:
    interfaces:
      Filter:
  github.com/aitra-ai/aitra-server/common/types:
    config:
    interfaces:
      SensitiveRequestV2:
  github.com/aitra-ai/aitra-server/mq:
    config:
    interfaces:
      MessageQueue:
  github.com/aitra-ai/aitra-server/builder/store/s3:
    config:
    interfaces:
      Client:
      Core:
  github.com/aitra-ai/aitra-server/builder/deploy:
    config:
    interfaces:
      Deployer:
  github.com/aitra-ai/aitra-server/builder/deploy/cluster:
    config:
    interfaces:
      Pool:
  github.com/aitra-ai/aitra-server/builder/deploy/scheduler:
    config:
    interfaces:
      Scheduler:
  github.com/aitra-ai/aitra-server/builder/deploy/imagerunner:
    config:
    interfaces:
      Runner:
  github.com/aitra-ai/aitra-server/builder/deploy/imagebuilder:
    config:
    interfaces:
      Builder:
  github.com/aitra-ai/aitra-server/accounting/component:
    config:
    interfaces:
      AccountingUserComponent:
      AccountingStatementComponent:
      AccountingBillComponent:
      AccountingPresentComponent:
      MeteringComponent:
      AccountingEventComponent:
      AccountingPriceComponent:
      AccountingOrderComponent:
      AccountingInvoiceComponent:
      StripeComponent:
      SubscriptionComponent:
  github.com/aitra-ai/aitra-server/builder/accounting:
    config:
    interfaces:
      AccountingClient:
  github.com/aitra-ai/aitra-server/builder/parquet:
    config:
    interfaces:
      Reader:
      LimitOffsetCountReader:
  github.com/aitra-ai/aitra-server/builder/multisync:
    config:
    interfaces:
      Client:
  github.com/aitra-ai/aitra-server/builder/store/cache:
    config:
    interfaces:
      RedisClient:
      LfsCache:
  github.com/aitra-ai/aitra-server/builder/captcha:
    config:
    interfaces:
      Interface:
  github.com/nats-io/nats.go/jetstream:
    config:
    interfaces:
      Msg:
  go.temporal.io/sdk/client:
    config:
    interfaces:
      Client:
  github.com/aitra-ai/aitra-server/builder/temporal:
    config:
    interfaces:
      Client:
      ScheduleClient:
  github.com/aitra-ai/aitra-server/builder/importer:
    config:
    interfaces:
      Importer:
  gitlab.com/gitlab-org/gitaly/v16/proto/go/gitalypb:
    config:
    interfaces:
      RepositoryServiceClient:
      CommitServiceClient:
      BlobServiceClient:
      RefServiceClient:
      DiffServiceClient:
      OperationServiceClient:
      SmartHTTPServiceClient:
      RemoteServiceClient:
  github.com/aitra-ai/aitra-server/builder/dataviewer:
    config:
    interfaces:
      DataviewerClient:
  github.com/aitra-ai/aitra-server/dataviewer/workflows:
    config:
    interfaces:
      DataViewerActivity:
  github.com/aitra-ai/aitra-server/dataviewer/component:
    config:
    interfaces:
      DatasetViewerComponent:
  github.com/aitra-ai/aitra-server/aigateway/component:
    config:
      all: true
  github.com/aitra-ai/aitra-server/aigateway/handler:
    config:
    interfaces:
      CommonResponseWriter:
      AgentAdapter:
  github.com/aitra-ai/aitra-server/aigateway/token:
    config:
      all: true
  github.com/aitra-ai/aitra-server/notification/component:
    config:
    interfaces:
      NotificationComponent:
      MailComponent:
  github.com/aitra-ai/aitra-server/notification/notifychannel/channel/lark/cache:
    interfaces:
      LarkCache:
  github.com/aitra-ai/aitra-server/notification/notifychannel/channel/lark/client:
    interfaces:
      LarkService:
  github.com/aitra-ai/aitra-server/runner/component:
    config:
    interfaces:
      ImagebuilderComponent:
      WorkFlowComponent:
      ServiceComponent:
      ClusterComponent:
  github.com/aitra-ai/aitra-server/logcollector/component:
    config:
      all: true
  github.com/aitra-ai/aitra-server/builder/mcp:
    config:
    interfaces:
      Client: